version: '3.9'

services:
  db:
    image: ankane/pgvector
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_streamlit
    restart: always
    environment:
      OPENAI_API_KEY: "sua_openai_api_key_aqui"
      DATABASE_URL: "postgresql://postgres:123@db:5432/mydatabase"
    ports:
      - "5000:5000"
      - "8501:8501"
    depends_on:
      - db

volumes:
  postgres_data:
